name: Node.js CI
on: push
jobs:
  build-node:
    runs-on: ubuntu-latest
    container: node:16
    steps:
      - name: Display Node.js version
        run: node --version
      - name: Display npm version
        run: npm --version
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Run the application
        run: node app.js
